### ISSUE TITLE
PEDstrata issue when strata not surveyed

### ISSUE THREAD

**Issue by freyakeyser** [Mar-scal/Assessment_fns#19]
In years when strata is not surveyed, PEDstrata ignores the strata entirely. It is excluded from the total area calculation, so some historical estimates may been too high. We also have some extra steps in survey.dat that need revising. See the following lines of code:

- summary_PEDstrata_annotated_for_reference_only: line 19
- survey.dat (for commercial N): lines 232-234

**Comment by Dave-Keith** [comment]
Turns out, this is actually fine with how this is handled offshore.  PEDStrata ignores strata that are not survey in estimating the numbers and biomass and comes up with an estimate per tow for the strata that are survey (yst).  For offshore in survey.dat (lines 232-234) we take this estimate and multiply it by the whole survey area, what we are implicitly assuming by doing this is that the estimate per tow calculcated in the surveyed areas applies to the un-surveyed strata.  This is a reasonable assumption.  Within PEDstrata itself a "Yst" is calculated which is the total abundance/biomass from the summary method but is only based on the areas that had a station surveyed (it outright ignores unsurveyed areas).  This will provide a good estimate for the strata that were surveyed, but does not account for the strata that was not surveyed. This will lead to PEDstrata underestimating total biomass as it does not account for unsurveyed strata areas.  For this reason if you have strata that are not sampled every year, you do not want to use the "Yst" object output from PEDstrata.
